### ISSUE TITLE
SSDT-EC-USBX problem

### ISSUE THREAD

**Issue by tangalbert919** [zacmks/Hackintosh-Aero-15X#12]
As of macOS 10.15 Catalina(or possibly earlier), the SSDT patch for Embedded Controllers do not work on most laptops, as explained [here](https://khronokernel.github.io/Getting-Started-With-ACPI/Laptops/laptop-ec.html).

I am currently trying to hackintosh my [Aero 15 Classic](https://www.gigabyte.com/Laptop/AERO-15-Classic--Intel-9th-Gen#kf), and making any modifications necessary to the files in this repo on my machine so I can boot macOS 10.15 successfully. I just want to know if your Aero 15X v8 was able to boot macOS 10.15 just fine with that SSDT patch for Embedded Controllers, as when I tried it on my Aero 15 Classic, it caused the boot process to hang

EDIT: I am attempting to do this with OpenCore.

**Comment by zacmks** [comment]
@tangalbert919, I haven't teste with Catalina, only Mojave.

On my case, renaming the EC (in our case we have ECDV and H_EC) were giving more problems compared to adding the EC device. As the embedded controller and it's signals on PC is quite different compared to MacOS (thus some devices can have different functions).

The problems included, weird sleep states, laptop not shutting down properly and unreliable boot.

Also, I read here, that we could add the EC device instead of renaming. As having the EC should suffice for Catalina:
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/intel-config.plist/coffee-lake

But yes, I haven't tested on Catalina myself and can't give much feedback

**Comment by zacmks** [comment]
Also, from OpenCore repository:
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-EC-USBX.dsl

`Try NOT to rename EC0, H_EC, etc. to EC.`

**Comment by zacmks** [comment]
Edit: in my case, it's ECDV, as it doesn't return zero for _STA (Aero 15X-V8, from my original DSDT.dsl/aml)

@tangalbert919, maybe your board could behave differently compared to mine?
As in your article it says:
`To fix the ECs found in laptops, we'll be renaming them to look like the ones macOS expects. The reason for this is that many laptops break when you turn off their EC with an SSDT`

And I think that disabling the EC should hang for the laptop independently of the OS version, just after applying the patch (which doesn't happen in my case) and on my case renaming was more detrimental than good for my laptop

**Comment by tangalbert919** [comment]
I tried that SSDT patch that would disable the EC, but it caused my laptop to just hang, so I had to rename the EC itself for it to work.

> on my case renaming was more detrimental than good for my laptop

Did you try to rename ECDV, H_EC, or both? I read the DSDT provided in this repo, and based on the article I sent, only ECDV would need to be renamed.

**Comment by zacmks** [comment]
@tangalbert919, oh yes, it was ECDV. I've re-checked it and my laptop doesn't have H_EC device (although it's on DSDT, it's status return zero)

It actually depends on your device, thus it depends on which ACPI paths actually available.
Do you mind sending me your DSDT?

But from what it looks, your device could be a different case compared to Aero 15X v8s

**Comment by tangalbert919** [comment]
My DSDT is [here](https://github.com/tangalbert919/Hackintosh-Aero-15-Classic/blob/master/patches/DSDT.dsl).

If you have Discord, this could be handled through the InsanelyHack server just to speed things up.

**Comment by zacmks** [comment]
In your case it's ECDV indeed. Like my board, H_EC returns zero for _STA (which means the device is disabled).

So, your computer doesn't like the current EC patch (the one on my repo, which disables ECDV).
Rename [as you are doing] should be the way to go.


OR, (you'll need to test). The same patch without "(\_SB.PCI0.LPCB.ECDV._STA)" returning zero, as follow:
```
DefinitionBlock ("", "SSDT", 2, "ACDT", "SsdtEC", 0x00001000)
{
    External (_SB_.PCI0.LPCB, DeviceObj)

    Scope (\_SB)
    {
        Device (USBX)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                If ((Arg2 == Zero))
                {
                    Return (Buffer (One)
                    {
                         0x03                                             // .
                    })
                }

                Return (Package (0x08)
                {
                    "kUSBSleepPowerSupply",
                    0x13EC,
                    "kUSBSleepPortCurrentLimit",
                    0x0834,
                    "kUSBWakePowerSupply",
                    0x13EC,
                    "kUSBWakePortCurrentLimit",
                    0x0834
                })
            }
        }

        Scope (\_SB.PCI0.LPCB)
        {
            Device (EC)
            {
                Name (_HID, "ACID0001")  // _HID: Hardware ID
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    If (_OSI ("Darwin"))
                    {
                        Return (0x0F)
                    }
                    Else
                    {
                        Return (Zero)
                    }
                }
            }
        }
    }
}
```
It'll keep your ECDV, and the added EC device. If it don't work, rename should be the best option for now. - Also, I kept the usb properties as I'm assuming you are using it from the same patch (if not, please disconsider it)

I have discord, but not using much lately bc of work stuff

Cheers, 
Isaac

**Comment by zacmks** [comment]
@tangalbert919, even if this last patch work I do suggest to test the stability for both cases.
- The rename method ECDV -> EC
- This patch that keeps ECDV and adds a new EC

**Comment by zacmks** [comment]
New EC rename method is now default, should boot Catalina

**Comment by tangalbert919** [comment]
I have managed to get macOS 10.15 working on my Aero 15 Classic, but I do not have the renaming method put in.

I'll just go ahead and close this, since this is no longer an issue for me.
