### ISSUE TITLE
No signs of battery indicator

### ISSUE THREAD

**Issue by aar0npham** [zacmks/Hackintosh-Aero-15X#14]
It seems to me that renaming EC has caused a lot of trouble with managing audio device/battery management. Any hotfix or such solution is to revert back to old version of OpenCore?

**Comment by zacmks** [comment]
Yes, it's here:
https://github.com/zacmks/Hackintosh-Aero-15X/commit/deb764c733625b9f2cf91cc2db8310c452ffdb80

patches/SSDT-BATT.dsl has been updated with new renamed path

**Comment by aar0npham** [comment]
@zacmks thank you for the fixes. I will close the issues here
