### ISSUE TITLE
Touchpad improvement with new elan kext

### ISSUE THREAD

**Issue by BAndysc** [zacmks/Hackintosh-Aero-15X#17]
> Better touchpad support (depends on kext update/release for ELAN touchpad)

for much much better (native gestures) for Elan, check my version of kext: https://github.com/BAndysc/VoodooPS2/releases/

**Comment by zacmks** [comment]
Thank you @BAndysc. It does recognize as Trackpad on macOS!

Just one question, is it normal for the pointer to move (not lock) when I do multifinger gestures with this kext?
Is there a config to improove it? Are there ways that I could help?

Thank you. Isaac

**Comment by BAndysc** [comment]
During most gestures (for instance two finger scrolling) pointer shouldn't move. Do you have multi finger gestures with this key? (2, 3, 4 finger gestures), do you have touchpad preference panel?

**Comment by zacmks** [comment]
Yess, I do have the Trackpad Preference panel.
With Trackpad Preferences, I tested the 2, 3, 4 finger gestures and most [if not all] of the gestures did work!

However, the pointer does move when doing the gestures, this is the behaviour that I get:
https://drive.google.com/file/d/1Bk75qA3hOv2HQFcs9Pr7xPreMYY0sNpE/view

**Comment by zacmks** [comment]
Did compile with your first "elanps2.v1" tag. And it's working amazingly thank you very much @BAndysc!!!

Unfortunatelly, all subsequent releases (0.2, 0.3, 0.4) had the issue with the pointer moving during gestures.

Closing with 7b0f4e09226b6d066c90684f1baaa93a84b5ad90 and 6170e3e9c003e65f15551236130cf5e7abd0005f
