### ISSUE TITLE
[REQUEST] Boot-chime. That's it, that's the request.

### ISSUE THREAD

**Issue by Malumen** [zacmks/Hackintosh-Aero-15X#25]
Hi @zacmks !  Thank you for keeping this repo updated!!

I have been struggling with trying to get the boot-sound to run at startup using the onboard speakers. If you could get it working and send me an updated `config.plist` so I can cross-compare and figure out what I am doing wrong. (I am going to delete all other sounds and really just want to get the boot-chime working)

https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-boot-chime-with-audiodxe

**Comment by zacmks** [comment]
Hello @Malumen, I was able to make it work once with the following config:
https://github.com/zacmks/Hackintosh-Aero-15X/commit/0077904260cdc1fcfa5aa1f43d1c806b0d814c55

It's a hit/miss situation on my side, I think that my rEFInd is affecting the boot sound.
From this config, you could try to change the following:
AudioOut - To test the available outputs
SetupDelay

Still investigating what it might be.

The details of my latest changes for audio were:
AudioDxe.efi driver added
AudioDevice pointing to intel audio pci address
A few adjustments on volume props

**Comment by zacmks** [comment]
Hi @Malumen, it should work with latest release (2.4.7)

On `config.plist`, just set `PlayChime`:
- from `Disabled` to `Auto`, or `Enabled`

Also, test the value of `AudioOut` between `0` and `1`

Afaik, from my tests: 0 is the speakers and 1 is headphones output
