### ISSUE TITLE
USB based devices lagging/stuttering

### ISSUE THREAD

**Issue by zacmks** [zacmks/Hackintosh-Aero-15X#3]
## Details of the issue

After complete installation, USB based devices does stutter/lags, this can be found devices such as:
- USB mouses
- USB keyboards
- Built-in USB keyboard
- On Logitech unifying mouses/keyboards (proprietary, dongle based)
- Bluetooth devices (uses USB bus)

**Notes:**
The evidence for bluetooth devices comes testing keyboards/mouses and having the exactly the same behavior as their USB only parts. Thus, bluetooth issues [solely] are discarded for now.
If the USB issue gets fixed, and it bluetooth devices issues persist I'll open another issue.

## Steps to reproduce

1. Have all the Hackintosh setup, with all patches kexts
2. Just use the computer regularly
3. Observe that mouse/keyboard does lag. For keyboards, it can just lag, or "get stuck" inputting several key inputs. (i.e. when typing a letter such as "e", it can get stuck for a while and instead do the input as eeeeeeeeeeeee)

Possible approaches to solve the issue:
- ~~Test variations for USB injection to see if this issue is solved (might have some good implication on powerdown as well)
https://github.com/zacmks/Hackintosh-Aero-15X/blob/master/10.13.6/patches/SSDT-UIAC.dsl~~
- ~~Test variations for USB PM patches:
https://github.com/zacmks/Hackintosh-Aero-15X/blob/master/10.13.6/patches/SSDT-USBX.dsl~~
- Add other ACPI patches

### Details, follow up:
https://www.tonymacx86.com/threads/help-gigabyte-aero-15x-usb-based-devices-lagging-stuttering.271029/

**Comment by zacmks** [comment]
Closing this, it was software related. I use Karabiner-Elements, which was the reason for the lags

**Comment by Malumen** [comment]
> Closing this, it was software related. I use Karabiner-Elements, which was the reason for the lags

Perhaps this is the reason I am getting the internal keyboard lagging (after an hour or two of use). I will try to disable it and see if it continues.
