### ISSUE TITLE
Wider compatibility?

### ISSUE THREAD

**Issue by brightplastik** [zacmks/Hackintosh-Aero-15X#31]
Hello Zacmks,
I'm using your repository with great satisfaction, and I shall give you all my admiration for this.

Question, though. I see the build you're testing is macOS Big Sur 11.3.1 (20E241), but it is virtually not available online.
Is it an old build because of some particular reason, or one could easily use, say, build number 11.6.1 (20G224) with no problem expected? I ask before, as I'm not to consider a hackintosh wise. I could not be able to roll over any big disfunctional change, so maybe before I try you tell me "no absolutely don't do it" and I'll be happy with my 11.2.3

Thanks for all your shared knowledge and wish you happiness,
Gabriel

**Comment by zacmks** [comment]
Thank you very much for the kind words @brightplastik :)

Yes, I "think" you can use 20G224, I do try to make the repo as compatible as possible (such as regular update OC config updates, making the repo compatible with original Apple's update).
But as a single person (and as a salaried employee) unfortunately I don't have the means or the time to do extra extensive tests on several versions. The only reason that I put the specific macOS version is that it's the version that I run on my personal machine at the time of the release. 

Now I see that 11.3.1 is indeed an old version, I'll try to update it when I get some time for me. Thank you :)

**Comment by zacmks** [comment]
Updated to macOS Big Sur 11.6.1 (20G224) with the latest release. Seems working fine

![image](https://user-images.githubusercontent.com/14233911/144789999-7933efe1-d5da-4228-88d1-c7b4450716e8.png)

I will close this issue now
Thank you for reporting @brightplastik 

PS: I had the SIP disabled and my macOS's "Software Update" showed as "Updated", looks like it's a behaviour to protect macOSs from a modified dmg/update/instalation
