### ISSUE TITLE
3 minutes backlight 

### ISSUE THREAD

**Issue by seyhaheng2** [zacmks/Hackintosh-Aero-15X#7]
How to solve that problem after I start my hackintosh I have to wait around 3 to 5 minutes for light is coming

**Comment by zacmks** [comment]
@seyhaheng2 no effective solutions yet as far as I know, please let me know if you find any

For now, you can use the hdmi port (with Nvidia graphics enabled) until the main screen turns on (it'll take the same 3 ~ 5 min for the main display turn on)
Or DP or monitor over thunderbolt - Those words with Intel graphics as well

**Comment by seyhaheng2** [comment]
It's working am if using Nvidia web driver?

**Comment by zacmks** [comment]
@seyhaheng2, yes Nvidia web drivers do work. It makes hdmi to work as well

Just remember to install Clover's rc scripts to save/restore the nvram, it's needed because the web driver checks the variables to see if they need to be loaded

**Comment by seyhaheng2** [comment]
when I try Mojave 10.14.3 the screen is working no need to wait but I can't fix Graphic UHD 630 31mb have you try it yet?

or can you help me to install 10.13.6 to working all I have also try your EFI but not working

**Comment by Jnss98b** [comment]
@zacmks To recap, the OS will boot up regularly but the built-in display will take 3-5 minutes to actually work?

**Comment by seyhaheng2** [comment]
Yes it's working 100% and if you don't mine you can remote TeamViewer to fixed my UHD 630 31mb

**Comment by seyhaheng2** [comment]
Yes it's working 100% and if you don't mine you can remote TeamViewer to fixed my UHD 630 31mb

**Comment by Jnss98b** [comment]
@seyhaheng2 Does this issue happen when you wake the laptop back from Sleep?

**Comment by seyhaheng2** [comment]
The issue is graphic just only 31mb

**Comment by Jnss98b** [comment]
@seyhaheng2 No, I was talking about the main issue that's the title of this thread.

**Comment by seyhaheng2** [comment]
The main issues is on 10.13.6 if now am using 10.4.3 so now the issue is graphic 31mb

**Comment by Jnss98b** [comment]
@seyhaheng2 Then make a new issue entry

**Comment by Jnss98b** [comment]
I'm confused. Why did you close this issue?
